//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechFix.AdminOrdersServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdminOrdersServiceReference.AdminOrdersWebServiceSoap")]
    public interface AdminOrdersWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name newStatus from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateOrderStatus", ReplyAction="*")]
        TechFix.AdminOrdersServiceReference.UpdateOrderStatusResponse UpdateOrderStatus(TechFix.AdminOrdersServiceReference.UpdateOrderStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateOrderStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFix.AdminOrdersServiceReference.UpdateOrderStatusResponse> UpdateOrderStatusAsync(TechFix.AdminOrdersServiceReference.UpdateOrderStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateOrderStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateOrderStatus", Namespace="http://tempuri.org/", Order=0)]
        public TechFix.AdminOrdersServiceReference.UpdateOrderStatusRequestBody Body;
        
        public UpdateOrderStatusRequest() {
        }
        
        public UpdateOrderStatusRequest(TechFix.AdminOrdersServiceReference.UpdateOrderStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateOrderStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string newStatus;
        
        public UpdateOrderStatusRequestBody() {
        }
        
        public UpdateOrderStatusRequestBody(int orderId, string newStatus) {
            this.orderId = orderId;
            this.newStatus = newStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateOrderStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateOrderStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFix.AdminOrdersServiceReference.UpdateOrderStatusResponseBody Body;
        
        public UpdateOrderStatusResponse() {
        }
        
        public UpdateOrderStatusResponse(TechFix.AdminOrdersServiceReference.UpdateOrderStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateOrderStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateOrderStatusResult;
        
        public UpdateOrderStatusResponseBody() {
        }
        
        public UpdateOrderStatusResponseBody(string UpdateOrderStatusResult) {
            this.UpdateOrderStatusResult = UpdateOrderStatusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AdminOrdersWebServiceSoapChannel : TechFix.AdminOrdersServiceReference.AdminOrdersWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminOrdersWebServiceSoapClient : System.ServiceModel.ClientBase<TechFix.AdminOrdersServiceReference.AdminOrdersWebServiceSoap>, TechFix.AdminOrdersServiceReference.AdminOrdersWebServiceSoap {
        
        public AdminOrdersWebServiceSoapClient() {
        }
        
        public AdminOrdersWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminOrdersWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminOrdersWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminOrdersWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFix.AdminOrdersServiceReference.UpdateOrderStatusResponse TechFix.AdminOrdersServiceReference.AdminOrdersWebServiceSoap.UpdateOrderStatus(TechFix.AdminOrdersServiceReference.UpdateOrderStatusRequest request) {
            return base.Channel.UpdateOrderStatus(request);
        }
        
        public string UpdateOrderStatus(int orderId, string newStatus) {
            TechFix.AdminOrdersServiceReference.UpdateOrderStatusRequest inValue = new TechFix.AdminOrdersServiceReference.UpdateOrderStatusRequest();
            inValue.Body = new TechFix.AdminOrdersServiceReference.UpdateOrderStatusRequestBody();
            inValue.Body.orderId = orderId;
            inValue.Body.newStatus = newStatus;
            TechFix.AdminOrdersServiceReference.UpdateOrderStatusResponse retVal = ((TechFix.AdminOrdersServiceReference.AdminOrdersWebServiceSoap)(this)).UpdateOrderStatus(inValue);
            return retVal.Body.UpdateOrderStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFix.AdminOrdersServiceReference.UpdateOrderStatusResponse> TechFix.AdminOrdersServiceReference.AdminOrdersWebServiceSoap.UpdateOrderStatusAsync(TechFix.AdminOrdersServiceReference.UpdateOrderStatusRequest request) {
            return base.Channel.UpdateOrderStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFix.AdminOrdersServiceReference.UpdateOrderStatusResponse> UpdateOrderStatusAsync(int orderId, string newStatus) {
            TechFix.AdminOrdersServiceReference.UpdateOrderStatusRequest inValue = new TechFix.AdminOrdersServiceReference.UpdateOrderStatusRequest();
            inValue.Body = new TechFix.AdminOrdersServiceReference.UpdateOrderStatusRequestBody();
            inValue.Body.orderId = orderId;
            inValue.Body.newStatus = newStatus;
            return ((TechFix.AdminOrdersServiceReference.AdminOrdersWebServiceSoap)(this)).UpdateOrderStatusAsync(inValue);
        }
    }
}
