//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechFix.CusOrderServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CusOrderServiceReference.CusOrderWebServiceSoap")]
    public interface CusOrderWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name SaveOrderResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveOrder", ReplyAction="*")]
        TechFix.CusOrderServiceReference.SaveOrderResponse SaveOrder(TechFix.CusOrderServiceReference.SaveOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFix.CusOrderServiceReference.SaveOrderResponse> SaveOrderAsync(TechFix.CusOrderServiceReference.SaveOrderRequest request);
        
        // CODEGEN: Generating message contract since element name AutoOrderIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoOrderId", ReplyAction="*")]
        TechFix.CusOrderServiceReference.AutoOrderIdResponse AutoOrderId(TechFix.CusOrderServiceReference.AutoOrderIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoOrderId", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFix.CusOrderServiceReference.AutoOrderIdResponse> AutoOrderIdAsync(TechFix.CusOrderServiceReference.AutoOrderIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveOrder", Namespace="http://tempuri.org/", Order=0)]
        public TechFix.CusOrderServiceReference.SaveOrderRequestBody Body;
        
        public SaveOrderRequest() {
        }
        
        public SaveOrderRequest(TechFix.CusOrderServiceReference.SaveOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SaveOrderRequestBody {
        
        public SaveOrderRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFix.CusOrderServiceReference.SaveOrderResponseBody Body;
        
        public SaveOrderResponse() {
        }
        
        public SaveOrderResponse(TechFix.CusOrderServiceReference.SaveOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SaveOrderResult;
        
        public SaveOrderResponseBody() {
        }
        
        public SaveOrderResponseBody(string SaveOrderResult) {
            this.SaveOrderResult = SaveOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoOrderIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoOrderId", Namespace="http://tempuri.org/", Order=0)]
        public TechFix.CusOrderServiceReference.AutoOrderIdRequestBody Body;
        
        public AutoOrderIdRequest() {
        }
        
        public AutoOrderIdRequest(TechFix.CusOrderServiceReference.AutoOrderIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AutoOrderIdRequestBody {
        
        public AutoOrderIdRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoOrderIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoOrderIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFix.CusOrderServiceReference.AutoOrderIdResponseBody Body;
        
        public AutoOrderIdResponse() {
        }
        
        public AutoOrderIdResponse(TechFix.CusOrderServiceReference.AutoOrderIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AutoOrderIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AutoOrderIdResult;
        
        public AutoOrderIdResponseBody() {
        }
        
        public AutoOrderIdResponseBody(string AutoOrderIdResult) {
            this.AutoOrderIdResult = AutoOrderIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CusOrderWebServiceSoapChannel : TechFix.CusOrderServiceReference.CusOrderWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CusOrderWebServiceSoapClient : System.ServiceModel.ClientBase<TechFix.CusOrderServiceReference.CusOrderWebServiceSoap>, TechFix.CusOrderServiceReference.CusOrderWebServiceSoap {
        
        public CusOrderWebServiceSoapClient() {
        }
        
        public CusOrderWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CusOrderWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CusOrderWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CusOrderWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFix.CusOrderServiceReference.SaveOrderResponse TechFix.CusOrderServiceReference.CusOrderWebServiceSoap.SaveOrder(TechFix.CusOrderServiceReference.SaveOrderRequest request) {
            return base.Channel.SaveOrder(request);
        }
        
        public string SaveOrder() {
            TechFix.CusOrderServiceReference.SaveOrderRequest inValue = new TechFix.CusOrderServiceReference.SaveOrderRequest();
            inValue.Body = new TechFix.CusOrderServiceReference.SaveOrderRequestBody();
            TechFix.CusOrderServiceReference.SaveOrderResponse retVal = ((TechFix.CusOrderServiceReference.CusOrderWebServiceSoap)(this)).SaveOrder(inValue);
            return retVal.Body.SaveOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFix.CusOrderServiceReference.SaveOrderResponse> TechFix.CusOrderServiceReference.CusOrderWebServiceSoap.SaveOrderAsync(TechFix.CusOrderServiceReference.SaveOrderRequest request) {
            return base.Channel.SaveOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFix.CusOrderServiceReference.SaveOrderResponse> SaveOrderAsync() {
            TechFix.CusOrderServiceReference.SaveOrderRequest inValue = new TechFix.CusOrderServiceReference.SaveOrderRequest();
            inValue.Body = new TechFix.CusOrderServiceReference.SaveOrderRequestBody();
            return ((TechFix.CusOrderServiceReference.CusOrderWebServiceSoap)(this)).SaveOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFix.CusOrderServiceReference.AutoOrderIdResponse TechFix.CusOrderServiceReference.CusOrderWebServiceSoap.AutoOrderId(TechFix.CusOrderServiceReference.AutoOrderIdRequest request) {
            return base.Channel.AutoOrderId(request);
        }
        
        public string AutoOrderId() {
            TechFix.CusOrderServiceReference.AutoOrderIdRequest inValue = new TechFix.CusOrderServiceReference.AutoOrderIdRequest();
            inValue.Body = new TechFix.CusOrderServiceReference.AutoOrderIdRequestBody();
            TechFix.CusOrderServiceReference.AutoOrderIdResponse retVal = ((TechFix.CusOrderServiceReference.CusOrderWebServiceSoap)(this)).AutoOrderId(inValue);
            return retVal.Body.AutoOrderIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFix.CusOrderServiceReference.AutoOrderIdResponse> TechFix.CusOrderServiceReference.CusOrderWebServiceSoap.AutoOrderIdAsync(TechFix.CusOrderServiceReference.AutoOrderIdRequest request) {
            return base.Channel.AutoOrderIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFix.CusOrderServiceReference.AutoOrderIdResponse> AutoOrderIdAsync() {
            TechFix.CusOrderServiceReference.AutoOrderIdRequest inValue = new TechFix.CusOrderServiceReference.AutoOrderIdRequest();
            inValue.Body = new TechFix.CusOrderServiceReference.AutoOrderIdRequestBody();
            return ((TechFix.CusOrderServiceReference.CusOrderWebServiceSoap)(this)).AutoOrderIdAsync(inValue);
        }
    }
}
