//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechFix.CusloginServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CusloginServiceReference.CusLoginWebServiceSoap")]
    public interface CusLoginWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateUser", ReplyAction="*")]
        TechFix.CusloginServiceReference.ValidateUserResponse ValidateUser(TechFix.CusloginServiceReference.ValidateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFix.CusloginServiceReference.ValidateUserResponse> ValidateUserAsync(TechFix.CusloginServiceReference.ValidateUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateUser", Namespace="http://tempuri.org/", Order=0)]
        public TechFix.CusloginServiceReference.ValidateUserRequestBody Body;
        
        public ValidateUserRequest() {
        }
        
        public ValidateUserRequest(TechFix.CusloginServiceReference.ValidateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public ValidateUserRequestBody() {
        }
        
        public ValidateUserRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFix.CusloginServiceReference.ValidateUserResponseBody Body;
        
        public ValidateUserResponse() {
        }
        
        public ValidateUserResponse(TechFix.CusloginServiceReference.ValidateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ValidateUserResult;
        
        public ValidateUserResponseBody() {
        }
        
        public ValidateUserResponseBody(bool ValidateUserResult) {
            this.ValidateUserResult = ValidateUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CusLoginWebServiceSoapChannel : TechFix.CusloginServiceReference.CusLoginWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CusLoginWebServiceSoapClient : System.ServiceModel.ClientBase<TechFix.CusloginServiceReference.CusLoginWebServiceSoap>, TechFix.CusloginServiceReference.CusLoginWebServiceSoap {
        
        public CusLoginWebServiceSoapClient() {
        }
        
        public CusLoginWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CusLoginWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CusLoginWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CusLoginWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFix.CusloginServiceReference.ValidateUserResponse TechFix.CusloginServiceReference.CusLoginWebServiceSoap.ValidateUser(TechFix.CusloginServiceReference.ValidateUserRequest request) {
            return base.Channel.ValidateUser(request);
        }
        
        public bool ValidateUser(string username, string password) {
            TechFix.CusloginServiceReference.ValidateUserRequest inValue = new TechFix.CusloginServiceReference.ValidateUserRequest();
            inValue.Body = new TechFix.CusloginServiceReference.ValidateUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            TechFix.CusloginServiceReference.ValidateUserResponse retVal = ((TechFix.CusloginServiceReference.CusLoginWebServiceSoap)(this)).ValidateUser(inValue);
            return retVal.Body.ValidateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFix.CusloginServiceReference.ValidateUserResponse> TechFix.CusloginServiceReference.CusLoginWebServiceSoap.ValidateUserAsync(TechFix.CusloginServiceReference.ValidateUserRequest request) {
            return base.Channel.ValidateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFix.CusloginServiceReference.ValidateUserResponse> ValidateUserAsync(string username, string password) {
            TechFix.CusloginServiceReference.ValidateUserRequest inValue = new TechFix.CusloginServiceReference.ValidateUserRequest();
            inValue.Body = new TechFix.CusloginServiceReference.ValidateUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((TechFix.CusloginServiceReference.CusLoginWebServiceSoap)(this)).ValidateUserAsync(inValue);
        }
    }
}
