//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechFix.OrderServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderServiceReference.OrderWebServiceSoap")]
    public interface OrderWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name SaveOrderResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveOrder", ReplyAction="*")]
        TechFix.OrderServiceReference.SaveOrderResponse SaveOrder(TechFix.OrderServiceReference.SaveOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFix.OrderServiceReference.SaveOrderResponse> SaveOrderAsync(TechFix.OrderServiceReference.SaveOrderRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveOrder", Namespace="http://tempuri.org/", Order=0)]
        public TechFix.OrderServiceReference.SaveOrderRequestBody Body;
        
        public SaveOrderRequest() {
        }
        
        public SaveOrderRequest(TechFix.OrderServiceReference.SaveOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SaveOrderRequestBody {
        
        public SaveOrderRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFix.OrderServiceReference.SaveOrderResponseBody Body;
        
        public SaveOrderResponse() {
        }
        
        public SaveOrderResponse(TechFix.OrderServiceReference.SaveOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SaveOrderResult;
        
        public SaveOrderResponseBody() {
        }
        
        public SaveOrderResponseBody(string SaveOrderResult) {
            this.SaveOrderResult = SaveOrderResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrderWebServiceSoapChannel : TechFix.OrderServiceReference.OrderWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderWebServiceSoapClient : System.ServiceModel.ClientBase<TechFix.OrderServiceReference.OrderWebServiceSoap>, TechFix.OrderServiceReference.OrderWebServiceSoap {
        
        public OrderWebServiceSoapClient() {
        }
        
        public OrderWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFix.OrderServiceReference.SaveOrderResponse TechFix.OrderServiceReference.OrderWebServiceSoap.SaveOrder(TechFix.OrderServiceReference.SaveOrderRequest request) {
            return base.Channel.SaveOrder(request);
        }
        
        public string SaveOrder() {
            TechFix.OrderServiceReference.SaveOrderRequest inValue = new TechFix.OrderServiceReference.SaveOrderRequest();
            inValue.Body = new TechFix.OrderServiceReference.SaveOrderRequestBody();
            TechFix.OrderServiceReference.SaveOrderResponse retVal = ((TechFix.OrderServiceReference.OrderWebServiceSoap)(this)).SaveOrder(inValue);
            return retVal.Body.SaveOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFix.OrderServiceReference.SaveOrderResponse> TechFix.OrderServiceReference.OrderWebServiceSoap.SaveOrderAsync(TechFix.OrderServiceReference.SaveOrderRequest request) {
            return base.Channel.SaveOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFix.OrderServiceReference.SaveOrderResponse> SaveOrderAsync() {
            TechFix.OrderServiceReference.SaveOrderRequest inValue = new TechFix.OrderServiceReference.SaveOrderRequest();
            inValue.Body = new TechFix.OrderServiceReference.SaveOrderRequestBody();
            return ((TechFix.OrderServiceReference.OrderWebServiceSoap)(this)).SaveOrderAsync(inValue);
        }
    }
}
