//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechFix.loginServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="loginServiceReference.loginWebServiceSoap")]
    public interface loginWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateUser", ReplyAction="*")]
        TechFix.loginServiceReference.ValidateUserResponse ValidateUser(TechFix.loginServiceReference.ValidateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFix.loginServiceReference.ValidateUserResponse> ValidateUserAsync(TechFix.loginServiceReference.ValidateUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateUser", Namespace="http://tempuri.org/", Order=0)]
        public TechFix.loginServiceReference.ValidateUserRequestBody Body;
        
        public ValidateUserRequest() {
        }
        
        public ValidateUserRequest(TechFix.loginServiceReference.ValidateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public ValidateUserRequestBody() {
        }
        
        public ValidateUserRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFix.loginServiceReference.ValidateUserResponseBody Body;
        
        public ValidateUserResponse() {
        }
        
        public ValidateUserResponse(TechFix.loginServiceReference.ValidateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ValidateUserResult;
        
        public ValidateUserResponseBody() {
        }
        
        public ValidateUserResponseBody(bool ValidateUserResult) {
            this.ValidateUserResult = ValidateUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface loginWebServiceSoapChannel : TechFix.loginServiceReference.loginWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class loginWebServiceSoapClient : System.ServiceModel.ClientBase<TechFix.loginServiceReference.loginWebServiceSoap>, TechFix.loginServiceReference.loginWebServiceSoap {
        
        public loginWebServiceSoapClient() {
        }
        
        public loginWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public loginWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public loginWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public loginWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFix.loginServiceReference.ValidateUserResponse TechFix.loginServiceReference.loginWebServiceSoap.ValidateUser(TechFix.loginServiceReference.ValidateUserRequest request) {
            return base.Channel.ValidateUser(request);
        }
        
        public bool ValidateUser(string username, string password) {
            TechFix.loginServiceReference.ValidateUserRequest inValue = new TechFix.loginServiceReference.ValidateUserRequest();
            inValue.Body = new TechFix.loginServiceReference.ValidateUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            TechFix.loginServiceReference.ValidateUserResponse retVal = ((TechFix.loginServiceReference.loginWebServiceSoap)(this)).ValidateUser(inValue);
            return retVal.Body.ValidateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFix.loginServiceReference.ValidateUserResponse> TechFix.loginServiceReference.loginWebServiceSoap.ValidateUserAsync(TechFix.loginServiceReference.ValidateUserRequest request) {
            return base.Channel.ValidateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFix.loginServiceReference.ValidateUserResponse> ValidateUserAsync(string username, string password) {
            TechFix.loginServiceReference.ValidateUserRequest inValue = new TechFix.loginServiceReference.ValidateUserRequest();
            inValue.Body = new TechFix.loginServiceReference.ValidateUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((TechFix.loginServiceReference.loginWebServiceSoap)(this)).ValidateUserAsync(inValue);
        }
    }
}
