//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechFix.SupOrderServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SupOrderServiceReference.CategoryWebServiceSoap")]
    public interface CategoryWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name AutoCategoryIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoCategoryId", ReplyAction="*")]
        TechFix.SupOrderServiceReference.AutoCategoryIdResponse AutoCategoryId(TechFix.SupOrderServiceReference.AutoCategoryIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoCategoryId", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFix.SupOrderServiceReference.AutoCategoryIdResponse> AutoCategoryIdAsync(TechFix.SupOrderServiceReference.AutoCategoryIdRequest request);
        
        // CODEGEN: Generating message contract since element name categoryId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertCategory", ReplyAction="*")]
        TechFix.SupOrderServiceReference.insertCategoryResponse insertCategory(TechFix.SupOrderServiceReference.insertCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFix.SupOrderServiceReference.insertCategoryResponse> insertCategoryAsync(TechFix.SupOrderServiceReference.insertCategoryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoCategoryIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoCategoryId", Namespace="http://tempuri.org/", Order=0)]
        public TechFix.SupOrderServiceReference.AutoCategoryIdRequestBody Body;
        
        public AutoCategoryIdRequest() {
        }
        
        public AutoCategoryIdRequest(TechFix.SupOrderServiceReference.AutoCategoryIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AutoCategoryIdRequestBody {
        
        public AutoCategoryIdRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoCategoryIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoCategoryIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFix.SupOrderServiceReference.AutoCategoryIdResponseBody Body;
        
        public AutoCategoryIdResponse() {
        }
        
        public AutoCategoryIdResponse(TechFix.SupOrderServiceReference.AutoCategoryIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AutoCategoryIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AutoCategoryIdResult;
        
        public AutoCategoryIdResponseBody() {
        }
        
        public AutoCategoryIdResponseBody(string AutoCategoryIdResult) {
            this.AutoCategoryIdResult = AutoCategoryIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertCategory", Namespace="http://tempuri.org/", Order=0)]
        public TechFix.SupOrderServiceReference.insertCategoryRequestBody Body;
        
        public insertCategoryRequest() {
        }
        
        public insertCategoryRequest(TechFix.SupOrderServiceReference.insertCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertCategoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string categoryId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string categoryName;
        
        public insertCategoryRequestBody() {
        }
        
        public insertCategoryRequestBody(string categoryId, string categoryName) {
            this.categoryId = categoryId;
            this.categoryName = categoryName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertCategoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFix.SupOrderServiceReference.insertCategoryResponseBody Body;
        
        public insertCategoryResponse() {
        }
        
        public insertCategoryResponse(TechFix.SupOrderServiceReference.insertCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertCategoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string insertCategoryResult;
        
        public insertCategoryResponseBody() {
        }
        
        public insertCategoryResponseBody(string insertCategoryResult) {
            this.insertCategoryResult = insertCategoryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CategoryWebServiceSoapChannel : TechFix.SupOrderServiceReference.CategoryWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CategoryWebServiceSoapClient : System.ServiceModel.ClientBase<TechFix.SupOrderServiceReference.CategoryWebServiceSoap>, TechFix.SupOrderServiceReference.CategoryWebServiceSoap {
        
        public CategoryWebServiceSoapClient() {
        }
        
        public CategoryWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CategoryWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoryWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoryWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFix.SupOrderServiceReference.AutoCategoryIdResponse TechFix.SupOrderServiceReference.CategoryWebServiceSoap.AutoCategoryId(TechFix.SupOrderServiceReference.AutoCategoryIdRequest request) {
            return base.Channel.AutoCategoryId(request);
        }
        
        public string AutoCategoryId() {
            TechFix.SupOrderServiceReference.AutoCategoryIdRequest inValue = new TechFix.SupOrderServiceReference.AutoCategoryIdRequest();
            inValue.Body = new TechFix.SupOrderServiceReference.AutoCategoryIdRequestBody();
            TechFix.SupOrderServiceReference.AutoCategoryIdResponse retVal = ((TechFix.SupOrderServiceReference.CategoryWebServiceSoap)(this)).AutoCategoryId(inValue);
            return retVal.Body.AutoCategoryIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFix.SupOrderServiceReference.AutoCategoryIdResponse> TechFix.SupOrderServiceReference.CategoryWebServiceSoap.AutoCategoryIdAsync(TechFix.SupOrderServiceReference.AutoCategoryIdRequest request) {
            return base.Channel.AutoCategoryIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFix.SupOrderServiceReference.AutoCategoryIdResponse> AutoCategoryIdAsync() {
            TechFix.SupOrderServiceReference.AutoCategoryIdRequest inValue = new TechFix.SupOrderServiceReference.AutoCategoryIdRequest();
            inValue.Body = new TechFix.SupOrderServiceReference.AutoCategoryIdRequestBody();
            return ((TechFix.SupOrderServiceReference.CategoryWebServiceSoap)(this)).AutoCategoryIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFix.SupOrderServiceReference.insertCategoryResponse TechFix.SupOrderServiceReference.CategoryWebServiceSoap.insertCategory(TechFix.SupOrderServiceReference.insertCategoryRequest request) {
            return base.Channel.insertCategory(request);
        }
        
        public string insertCategory(string categoryId, string categoryName) {
            TechFix.SupOrderServiceReference.insertCategoryRequest inValue = new TechFix.SupOrderServiceReference.insertCategoryRequest();
            inValue.Body = new TechFix.SupOrderServiceReference.insertCategoryRequestBody();
            inValue.Body.categoryId = categoryId;
            inValue.Body.categoryName = categoryName;
            TechFix.SupOrderServiceReference.insertCategoryResponse retVal = ((TechFix.SupOrderServiceReference.CategoryWebServiceSoap)(this)).insertCategory(inValue);
            return retVal.Body.insertCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFix.SupOrderServiceReference.insertCategoryResponse> TechFix.SupOrderServiceReference.CategoryWebServiceSoap.insertCategoryAsync(TechFix.SupOrderServiceReference.insertCategoryRequest request) {
            return base.Channel.insertCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFix.SupOrderServiceReference.insertCategoryResponse> insertCategoryAsync(string categoryId, string categoryName) {
            TechFix.SupOrderServiceReference.insertCategoryRequest inValue = new TechFix.SupOrderServiceReference.insertCategoryRequest();
            inValue.Body = new TechFix.SupOrderServiceReference.insertCategoryRequestBody();
            inValue.Body.categoryId = categoryId;
            inValue.Body.categoryName = categoryName;
            return ((TechFix.SupOrderServiceReference.CategoryWebServiceSoap)(this)).insertCategoryAsync(inValue);
        }
    }
}
